#include "../BackendServerFiles/Crow/include/crow.h"
#include "ApiServer.hpp"
#include "../engine/include/OrderBookSnapshot.hpp"
#include "../engine/include/TradeBook.hpp"
#include "../engine/include/StatisticsBook.hpp"
#include "../engine/include/Order.hpp"

#include "../BackendServerFiles/Crow/include/crow/middlewares/cors.h"

#include<cstdlib>


ApiServer::ApiServer(Exchange *exchange)
{
    this->exchange=exchange;
}
void ApiServer::start()
{
    // crow::SimpleApp App;//we have CORS MIDDLEWARE IN OUR CROW
    crow::App<crow::CORSHandler>App;

    App.get_middleware<crow::CORSHandler>().global().origin("*")
    .methods(crow::HTTPMethod::GET,
            crow::HTTPMethod::POST,
            crow::HTTPMethod::OPTIONS).headers("Content-Type");





    CROW_ROUTE(App,"/")
    ([](){
        return "Welcome to our Order Matching Engine";
    });
    CROW_ROUTE(App,"/orders/<string>")//view orders
    ([this](string stock){
        OrderBookSnapshot Obs=this->exchange->getOrderBook(stock);
        crow::json::wvalue response;
        response["stockName"]=Obs.stockName;
        response["bestBid"]=Obs.bestBid;
        response["bestAsk"]=Obs.bestAsk;
        crow::json::wvalue::list jsonArr;
        for(int i=0;i<Obs.buyLevels.size();i++)
        {
            //vector of priceLevels only
            crow::json::wvalue jsonObject;
            jsonObject["priceLevel"]=Obs.buyLevels[i].priceLevel;
            jsonObject["totalQuantity"]=Obs.buyLevels[i].quantity;

            jsonArr.push_back(jsonObject);

        }

        response["buyLevels"]=move(jsonArr);

        crow::json::wvalue::list jsonArr2;
        for(int i=0;i<Obs.sellLevels.size();i++)
        {
            //vector of priceLevels only
            crow::json::wvalue jsonObject;
            jsonObject["priceLevel"]=Obs.sellLevels[i].priceLevel;
            jsonObject["totalQuantity"]=Obs.sellLevels[i].quantity;

            jsonArr2.push_back(jsonObject);

        }
        response["sellLevels"]=move(jsonArr2);

       

        return response;

    });

    CROW_ROUTE(App,"/trades/<string>")
    ([this](string stock){
        //we need vector of trades for this orderbook
        TradeBook Tb=this->exchange->getTradeBook(stock);
        crow::json::wvalue response;

        response["totalTrades"]=Tb.totalTrades;
        crow::json::wvalue::list jsonArrTrades;
        for(int i=0;i<Tb.Trades.size();i++)
        {
            crow::json::wvalue jsonObject;

            jsonObject["stockName"]=Tb.Trades[i].stockName;
            jsonObject["tradeId"]=Tb.Trades[i].tradeId;
            jsonObject["buyOrderId"]=Tb.Trades[i].buyOrderId;
            jsonObject["sellOrderId"]=Tb.Trades[i].sellOrderId;
            jsonObject["tradingQuantity"]=Tb.Trades[i].quantity;
            jsonObject["tradePrice"]=Tb.Trades[i].tradePrice;
            jsonObject["timeStamp"]=Tb.Trades[i].time_stamp;
            
            jsonArrTrades.push_back(jsonObject);
            
            
        }
        response["Trades"]=move(jsonArrTrades);
        return response;
    });

    CROW_ROUTE(App,"/statistics/<string>")
    ([this](string stock){
        StatisticsBook sb=this->exchange->getStatisticsBook(stock);
        crow::json::wvalue response;
        response["stockName"]=stock;
        response["ordersReceived"]=sb.ordersReceived;
        response["ordersCancelled"]=sb.ordersCancelled;

        response["totalTrades"]=sb.totalTrades;
        response["totalTradedQuantity"]=sb.totalTradedQuantity;
        response["totalTradedValue"]=sb.totalTradedValue;

        response["activeBuyOrders"]=sb.activeBuyOrders;
        response["activeSellOrders"]=sb.activeSellOrders;
        response["bestAsk"]=sb.bestAsk;
        response["bestBid"]=sb.bestBid;

        response["buyVolume"]=sb.buyVolume;
        response["sellVolume"]=sb.sellVolume;

        return response;
    });
     

    CROW_ROUTE(App,"/placeOrder").methods(crow::HTTPMethod::POST)
    ([this](const crow::request &req){
        auto body=crow::json::load(req.body);

        if(!body)//body is not json file
        {
            return crow::response(400,"Invalid JSON File");
        }
        string stockName=body["stockName"].s();
        // int orderId=body["orderId"].i();//this shd be uniquely generated by exchange
        string side=body["side"].s();
        string type=body["type"].s();
        int price=body["price"].i();
        int quantity=body["quantity"].i();

        Order order;
        order.stockName=stockName;
        order.price=price;
        order.quantity=quantity;
        BuyOrSell sideEnum;
        if(side=="BUY" || side=="buy")
        {
            sideEnum=BuyOrSell::BUY;
        }
        else if(side=="SELL" || side=="sell")
        {
            sideEnum=BuyOrSell::SELL;
        }
        

        order.side=sideEnum;

        OrderType typeEnum;
        if(type=="LIMIT" || type=="limit")
        {
            typeEnum=OrderType::LIMIT;
        }
        else if(type=="MARKET" || type=="market")
        {
            typeEnum=OrderType::MARKET;
        }
        else if(type=="FOK" || type=="fok")
        {
            typeEnum=OrderType::FOK;
        }
        else if(type=="IOC" || type=="ioc")
        {
            typeEnum=OrderType::IOC;
        }
        

        order.type=typeEnum;
        
        this->exchange->placeOrder(order);

        crow::json::wvalue response;

        response["status"]="Success";
        response["msg"]="Order Placed Succesfully";
        return crow::response(response);
   
    });

   

    CROW_ROUTE(App,"/cancelOrder").methods(crow::HTTPMethod::POST)
    ([this](const crow::request &req){
        auto body=crow::json::load(req.body);

        if(!body)//body is not json file
        {
            return crow::response(400,"Invalid JSON File");
        }
        int orderId=body["orderId"].i();
        string stockName=body["stockName"].s();
        string side=body["side"].s();
        BuyOrSell sideEnum;
        if(side=="BUY" || side=="buy")
        {
            sideEnum=BuyOrSell::BUY;
        }
        else if(side=="SELL" || side=="sell")
        {
            sideEnum=BuyOrSell::SELL;
        }
        int OrderExist=this->exchange->cancelOrder(orderId,stockName,sideEnum);
        crow::json::wvalue response;
        response["status"]="Success";
        if(OrderExist!=0)
        {
            
            response["msg"]="Order Cancelled Succesfully";

        }
        else
        {
            response["msg"]="OrderId not exist for this side or stock not recognized";
        }

        return crow::response(response);


        
    });
    CROW_ROUTE(App,"/stressTest/<int>")
    ([this](int testOrders){
        int result=this->exchange->performStressTest(testOrders,exchange);
        crow::json::wvalue response;
        if(result==1)
        {
            response["IntegrityStatus"]="passed";

        }
        else if(result==0)
        {
            response["IntegrityStatus"]="failed";
        }
        else if(result==10)
        {
            response["IntegrityStatus"]="    ";
            response["msg"]="plz enter a no in range 1-1000000";
        }
        return response;
        
    });
    
    const char* envPort=getenv("PORT");//give pointer to port in the running environment if exist if not then nUL
    int port= envPort?stoi(envPort):18000;
    App.port(port).multithreaded().run();


}